//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEM {

public class FOFEM {
  public static void CI_Init(d_CI a_CI) {
    FOFEMPINVOKE.CI_Init(d_CI.getCPtr(a_CI));
  }

  public static int CI_isSpring(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSpring(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isFall(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isFall(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isWinter(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isWinter(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSummer(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSummer(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSeason(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSeason(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isShrubGroup(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isShrubGroup(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isShrubGroupChaparral(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isShrubGroupChaparral(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isGrassGroup(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isGrassGroup(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSageBrush(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSageBrush(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPocosin(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isPocosin(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPonderosa(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isPonderosa(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isWhiPinHem(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isWhiPinHem(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isRedJacPin(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isRedJacPin(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isBalBRWSpr(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isBalBRWSpr(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isCoastPlain(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isCoastPlain(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPinFlaWoo(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isPinFlaWoo(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isCoverGroup(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isCoverGroup(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSouthEast(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSouthEast(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isInteriorWest(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isInteriorWest(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPacificWest(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isPacificWest(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isNorthEast(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isNorthEast(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isNatural(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isNatural(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPiles(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isPiles(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSlash(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isSlash(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufEntire(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufEntire(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufLower(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufLower(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufNFDR(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufNFDR(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufAdjNFDR(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufAdjNFDR(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufMethod(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufMethod(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDuffWet(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_isDuffWet(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static void CI_Display(d_CI a_CI) {
    FOFEMPINVOKE.CI_Display(d_CI.getCPtr(a_CI));
  }

  public static float CI_MaxLoad(d_CI a_CI) {
    float ret = FOFEMPINVOKE.CI_MaxLoad(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static int CI_OnlyDuff(d_CI a_CI) {
    int ret = FOFEMPINVOKE.CI_OnlyDuff(d_CI.getCPtr(a_CI));
    return ret;
  }

  public static SWIGTYPE_p_FILE SI_fopen(string cr_FN, string cr) {
    global::System.IntPtr cPtr = FOFEMPINVOKE.SI_fopen(cr_FN, cr);
    SWIGTYPE_p_FILE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FILE(cPtr, false);
    return ret;
  }

  public static void SI_fprintfVal(SWIGTYPE_p_FILE fh, string cr_Fmt, float r_time) {
    FOFEMPINVOKE.SI_fprintfVal(SWIGTYPE_p_FILE.getCPtr(fh), cr_Fmt, r_time);
  }

  public static void SI_fprintfRet(SWIGTYPE_p_FILE fh, string cr_Ret) {
    FOFEMPINVOKE.SI_fprintfRet(SWIGTYPE_p_FILE.getCPtr(fh), cr_Ret);
  }

  public static void SI_fclose(SWIGTYPE_p_FILE fh) {
    FOFEMPINVOKE.SI_fclose(SWIGTYPE_p_FILE.getCPtr(fh));
  }

  public static void SI_Init(d_SI a_SI) {
    FOFEMPINVOKE.SI_Init(d_SI.getCPtr(a_SI));
  }

  public static void SO_Init(d_SO a_SO) {
    FOFEMPINVOKE.SO_Init(d_SO.getCPtr(a_SO));
  }

  public static int SH_Mngr(d_SI a_SI, d_SO a_SO, SWIGTYPE_p_float fr_FI, SWIGTYPE_p_float fr_FIhs, string cr_TmpPth, string cr_ErrMes) {
    int ret = FOFEMPINVOKE.SH_Mngr(d_SI.getCPtr(a_SI), d_SO.getCPtr(a_SO), SWIGTYPE_p_float.getCPtr(fr_FI), SWIGTYPE_p_float.getCPtr(fr_FIhs), cr_TmpPth, cr_ErrMes);
    return ret;
  }

  public static int NES_Read(string cr_Path, string cr_ErrMes) {
    int ret = FOFEMPINVOKE.NES_Read(cr_Path, cr_ErrMes);
    return ret;
  }

  public static int NES_Get_Factor(string cr_GrpNum, int ix, string cr_CovTyp, SWIGTYPE_p_float af_Factor, string cr_Name, string cr_Code) {
    int ret = FOFEMPINVOKE.NES_Get_Factor(cr_GrpNum, ix, cr_CovTyp, SWIGTYPE_p_float.getCPtr(af_Factor), cr_Name, cr_Code);
    return ret;
  }

  public static void NCT_Display() {
    FOFEMPINVOKE.NCT_Display();
  }

  public static void NES_Display() {
    FOFEMPINVOKE.NES_Display();
  }

  public static int NES_GetGrpCov(int ix, string cr_GrpNum, string cr_CovTyp, SWIGTYPE_p_int aiS_Def) {
    int ret = FOFEMPINVOKE.NES_GetGrpCov(ix, cr_GrpNum, cr_CovTyp, SWIGTYPE_p_int.getCPtr(aiS_Def));
    return ret;
  }

  public static int NES_Get_MajFactor(string cr_GrpNum, SWIGTYPE_p_float CO, SWIGTYPE_p_float CO2, SWIGTYPE_p_float CH4, SWIGTYPE_p_float PM25, SWIGTYPE_p_float PM10, SWIGTYPE_p_float NOX, SWIGTYPE_p_float SO2) {
    int ret = FOFEMPINVOKE.NES_Get_MajFactor(cr_GrpNum, SWIGTYPE_p_float.getCPtr(CO), SWIGTYPE_p_float.getCPtr(CO2), SWIGTYPE_p_float.getCPtr(CH4), SWIGTYPE_p_float.getCPtr(PM25), SWIGTYPE_p_float.getCPtr(PM10), SWIGTYPE_p_float.getCPtr(NOX), SWIGTYPE_p_float.getCPtr(SO2));
    return ret;
  }

  public static float NES_Get_CriFirInt() {
    float ret = FOFEMPINVOKE.NES_Get_CriFirInt();
    return ret;
  }

  public static readonly double e_DufMin = FOFEMPINVOKE.e_DufMin_get();
  public static readonly double e_DufMax = FOFEMPINVOKE.e_DufMax_get();
  public static readonly double e_DufDepMin = FOFEMPINVOKE.e_DufDepMin_get();
  public static readonly double e_DufDepMax = FOFEMPINVOKE.e_DufDepMax_get();
  public static readonly double e_MoiDW10Min = FOFEMPINVOKE.e_MoiDW10Min_get();
  public static readonly double e_MoiDW10Max = FOFEMPINVOKE.e_MoiDW10Max_get();
  public static readonly double e_LitMoiMin = FOFEMPINVOKE.e_LitMoiMin_get();
  public static readonly double e_LitMoiMax = FOFEMPINVOKE.e_LitMoiMax_get();
  public static readonly int eC_WD = FOFEMPINVOKE.eC_WD_get();
  public static readonly string e_GrassGroup = FOFEMPINVOKE.e_GrassGroup_get();
  public static readonly string e_SageBrush = FOFEMPINVOKE.e_SageBrush_get();
  public static readonly string e_ShrubGroup = FOFEMPINVOKE.e_ShrubGroup_get();
  public static readonly string e_ShrubGroupChaparral = FOFEMPINVOKE.e_ShrubGroupChaparral_get();
  public static readonly string e_Pocosin = FOFEMPINVOKE.e_Pocosin_get();
  public static readonly string e_Ponderosa = FOFEMPINVOKE.e_Ponderosa_get();
  public static readonly string e_WhiPinHem = FOFEMPINVOKE.e_WhiPinHem_get();
  public static readonly string e_RedJacPin = FOFEMPINVOKE.e_RedJacPin_get();
  public static readonly string e_BalBRWSpr = FOFEMPINVOKE.e_BalBRWSpr_get();
  public static readonly string e_PinFlaWoo = FOFEMPINVOKE.e_PinFlaWoo_get();
  public static readonly string e_CoastPlain = FOFEMPINVOKE.e_CoastPlain_get();
  public static readonly string e_CVT_GrassGroup = FOFEMPINVOKE.e_CVT_GrassGroup_get();
  public static readonly string e_CVT_SageBrush = FOFEMPINVOKE.e_CVT_SageBrush_get();
  public static readonly string e_CVT_ShrubGroup = FOFEMPINVOKE.e_CVT_ShrubGroup_get();
  public static readonly string e_CVT_ShrubGroupChaparral = FOFEMPINVOKE.e_CVT_ShrubGroupChaparral_get();
  public static readonly string e_CVT_Pocosin = FOFEMPINVOKE.e_CVT_Pocosin_get();
  public static readonly string e_CVT_Ponderosa = FOFEMPINVOKE.e_CVT_Ponderosa_get();
  public static readonly string e_CVT_WhiPinHem = FOFEMPINVOKE.e_CVT_WhiPinHem_get();
  public static readonly string e_CVT_RedJacPin = FOFEMPINVOKE.e_CVT_RedJacPin_get();
  public static readonly string e_CVT_BalBRWSpr = FOFEMPINVOKE.e_CVT_BalBRWSpr_get();
  public static readonly string e_CVT_PinFlaWoo = FOFEMPINVOKE.e_CVT_PinFlaWoo_get();
  public static readonly string e_CVT_CoastPlain = FOFEMPINVOKE.e_CVT_CoastPlain_get();
  public static readonly string GRASSGROUP = FOFEMPINVOKE.GRASSGROUP_get();
  public static readonly string SAGEBRUSH = FOFEMPINVOKE.SAGEBRUSH_get();
  public static readonly string SHRUBGROUP = FOFEMPINVOKE.SHRUBGROUP_get();
  public static readonly string POCOSIN = FOFEMPINVOKE.POCOSIN_get();
  public static readonly string PONDEROSA = FOFEMPINVOKE.PONDEROSA_get();
  public static readonly string WHIPINHEM = FOFEMPINVOKE.WHIPINHEM_get();
  public static readonly string REDJACPIN = FOFEMPINVOKE.REDJACPIN_get();
  public static readonly string BALBRWSPR = FOFEMPINVOKE.BALBRWSPR_get();
  public static readonly string PINFLAWOO = FOFEMPINVOKE.PINFLAWOO_get();
  public static readonly string COASTPLAIN = FOFEMPINVOKE.COASTPLAIN_get();
  public static readonly int eC_CoverGroup = FOFEMPINVOKE.eC_CoverGroup_get();
  public static readonly string e_CI_SAF = FOFEMPINVOKE.e_CI_SAF_get();
  public static readonly string e_CI_NVCS = FOFEMPINVOKE.e_CI_NVCS_get();
  public static readonly string e_CI_FCC = FOFEMPINVOKE.e_CI_FCC_get();
  public static readonly string e_CI_FLM = FOFEMPINVOKE.e_CI_FLM_get();
  public static readonly string e_CI_DefaultCoverClass = FOFEMPINVOKE.e_CI_DefaultCoverClass_get();
  public static readonly string e_Winter = FOFEMPINVOKE.e_Winter_get();
  public static readonly string e_Spring = FOFEMPINVOKE.e_Spring_get();
  public static readonly string e_Summer = FOFEMPINVOKE.e_Summer_get();
  public static readonly string e_Fall = FOFEMPINVOKE.e_Fall_get();
  public static readonly string WINTER = FOFEMPINVOKE.WINTER_get();
  public static readonly string SPRING = FOFEMPINVOKE.SPRING_get();
  public static readonly string SUMMER = FOFEMPINVOKE.SUMMER_get();
  public static readonly string FALL = FOFEMPINVOKE.FALL_get();
  public static readonly string e_SeasonDefault = FOFEMPINVOKE.e_SeasonDefault_get();
  public static readonly int eC_Season = FOFEMPINVOKE.eC_Season_get();
  public static readonly string e_CI_SouthEast = FOFEMPINVOKE.e_CI_SouthEast_get();
  public static readonly string e_CI_InteriorWest = FOFEMPINVOKE.e_CI_InteriorWest_get();
  public static readonly string e_CI_PacificWest = FOFEMPINVOKE.e_CI_PacificWest_get();
  public static readonly string e_CI_NorthEast = FOFEMPINVOKE.e_CI_NorthEast_get();
  public static readonly string SOUTHEAST = FOFEMPINVOKE.SOUTHEAST_get();
  public static readonly string INTERIORWEST = FOFEMPINVOKE.INTERIORWEST_get();
  public static readonly string PACIFICWEST = FOFEMPINVOKE.PACIFICWEST_get();
  public static readonly string NORTHEAST = FOFEMPINVOKE.NORTHEAST_get();
  public static readonly int eC_Region = FOFEMPINVOKE.eC_Region_get();
  public static readonly string e_Natural = FOFEMPINVOKE.e_Natural_get();
  public static readonly string e_Piles = FOFEMPINVOKE.e_Piles_get();
  public static readonly string e_Slash = FOFEMPINVOKE.e_Slash_get();
  public static readonly string NATURAL = FOFEMPINVOKE.NATURAL_get();
  public static readonly string PILES = FOFEMPINVOKE.PILES_get();
  public static readonly string SLASH = FOFEMPINVOKE.SLASH_get();
  public static readonly string e_FuelCategoryDefault = FOFEMPINVOKE.e_FuelCategoryDefault_get();
  public static readonly int eC_FuelCategory = FOFEMPINVOKE.eC_FuelCategory_get();
  public static readonly string e_Entire = FOFEMPINVOKE.e_Entire_get();
  public static readonly string e_Lower = FOFEMPINVOKE.e_Lower_get();
  public static readonly string e_NFDR = FOFEMPINVOKE.e_NFDR_get();
  public static readonly string e_Adj_NFDR = FOFEMPINVOKE.e_Adj_NFDR_get();
  public static readonly string ENTIRE = FOFEMPINVOKE.ENTIRE_get();
  public static readonly string LOWER = FOFEMPINVOKE.LOWER_get();
  public static readonly string NFDR = FOFEMPINVOKE.NFDR_get();
  public static readonly string ADJ_NFDR = FOFEMPINVOKE.ADJ_NFDR_get();
  public static readonly string e_DufMoiMetDefault = FOFEMPINVOKE.e_DufMoiMetDefault_get();
  public static readonly int eC_DufMoiMet = FOFEMPINVOKE.eC_DufMoiMet_get();
  public static readonly int e_EqMissing = FOFEMPINVOKE.e_EqMissing_get();
  public static readonly int e_EqDefault = FOFEMPINVOKE.e_EqDefault_get();
  public static readonly int eC_sfi = FOFEMPINVOKE.eC_sfi_get();
  public static readonly string e_SoiSimFail = FOFEMPINVOKE.e_SoiSimFail_get();
  public static readonly string e_SoilErr = FOFEMPINVOKE.e_SoilErr_get();
  public static readonly string e_FrameSFN = FOFEMPINVOKE.e_FrameSFN_get();
  public static readonly string e_FrameSstart = FOFEMPINVOKE.e_FrameSstart_get();
  public static readonly string e_FrameSend = FOFEMPINVOKE.e_FrameSend_get();
  public static readonly int e_Max1 = FOFEMPINVOKE.e_Max1_get();
  public static readonly int e_Max2 = FOFEMPINVOKE.e_Max2_get();
  public static readonly int e_mplus1 = FOFEMPINVOKE.e_mplus1_get();
  public static readonly int e_Layers = FOFEMPINVOKE.e_Layers_get();
  public static readonly string e_LoaSke = FOFEMPINVOKE.e_LoaSke_get();
  public static readonly string e_FinSil = FOFEMPINVOKE.e_FinSil_get();
  public static readonly string e_Fin = FOFEMPINVOKE.e_Fin_get();
  public static readonly string e_CoaSil = FOFEMPINVOKE.e_CoaSil_get();
  public static readonly string e_CoaLoa = FOFEMPINVOKE.e_CoaLoa_get();
  public static readonly string LOAMY_SKELETAL = FOFEMPINVOKE.LOAMY_SKELETAL_get();
  public static readonly string FINE_SILT = FOFEMPINVOKE.FINE_SILT_get();
  public static readonly string FINE = FOFEMPINVOKE.FINE_get();
  public static readonly string COARSE_SILT = FOFEMPINVOKE.COARSE_SILT_get();
  public static readonly string COARSE_LOAMY = FOFEMPINVOKE.COARSE_LOAMY_get();
  public static readonly int eC_SoilType = FOFEMPINVOKE.eC_SoilType_get();
  public static readonly string e_VeryDry = FOFEMPINVOKE.e_VeryDry_get();
  public static readonly string e_Dry = FOFEMPINVOKE.e_Dry_get();
  public static readonly string e_Moderate = FOFEMPINVOKE.e_Moderate_get();
  public static readonly string e_Wet = FOFEMPINVOKE.e_Wet_get();
  public static readonly string VERY_DRY = FOFEMPINVOKE.VERY_DRY_get();
  public static readonly string DRY = FOFEMPINVOKE.DRY_get();
  public static readonly string MODERATE = FOFEMPINVOKE.MODERATE_get();
  public static readonly string WET = FOFEMPINVOKE.WET_get();
  public static readonly int eC_MoistCond = FOFEMPINVOKE.eC_MoistCond_get();
  public static readonly int e_LayNone = FOFEMPINVOKE.e_LayNone_get();
  public static readonly string e_SM_Duff = FOFEMPINVOKE.e_SM_Duff_get();
  public static readonly string e_SM_ZDuff = FOFEMPINVOKE.e_SM_ZDuff_get();
  public static readonly double e_CriInt = FOFEMPINVOKE.e_CriInt_get();
  public static readonly string e_EmiFN = FOFEMPINVOKE.e_EmiFN_get();
  public static readonly string e_DefFlaGrp = FOFEMPINVOKE.e_DefFlaGrp_get();
  public static readonly string e_DefDufGrp = FOFEMPINVOKE.e_DefDufGrp_get();
  public static readonly string e_DefSmoGrp = FOFEMPINVOKE.e_DefSmoGrp_get();
}

}
